/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment_java3;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {
public static Main main;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        mnDiemSV.setEnabled(true);
        mnSV.setEnabled(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnDN = new javax.swing.JMenu();
        mnQL = new javax.swing.JMenu();
        mnDiemSV = new javax.swing.JMenuItem();
        mnSV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        mnDN.setText("Đăng nhập");
        mnDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDNMouseClicked(evt);
            }
        });
        mnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDNActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnDN);

        mnQL.setText("Quản lý");

        mnDiemSV.setText("Quản Lý Điểm Sinh Viên");
        mnDiemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiemSVActionPerformed(evt);
            }
        });
        mnQL.add(mnDiemSV);

        mnSV.setText("Quản Lý Sinh Viên");
        mnSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSVActionPerformed(evt);
            }
        });
        mnQL.add(mnSV);

        jMenuBar1.add(mnQL);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSVActionPerformed
        // TODO add your handling code here:
        QuanLySinhVien qlsv=new QuanLySinhVien();
        desktop.removeAll();
        desktop.add(qlsv);
        qlsv.setVisible(true);
    }//GEN-LAST:event_mnSVActionPerformed

    private void mnDiemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiemSVActionPerformed
        // TODO add your handling code here:
        QuanLyDiemSinhVien qldsv;
    try {
        qldsv = new QuanLyDiemSinhVien();
         desktop.removeAll();
        desktop.add(qldsv);
        qldsv.setVisible(true);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_mnDiemSVActionPerformed

    private void mnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDNActionPerformed
        // TODO add your handling code here:
        Login login=new Login();
        desktop.removeAll();
        desktop.add(login);
        login.setVisible(true);
    }//GEN-LAST:event_mnDNActionPerformed

    private void mnDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDNMouseClicked
        // TODO add your handling code here:
        Login login=new Login();
        desktop.removeAll();
        desktop.add(login);
        login.setVisible(true);
    }//GEN-LAST:event_mnDNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main =new Main();
                main.setVisible(true);
            }
        });
    }
    public void close(){
        main.setVisible(false);
    }
    public void GiaoVien(){
        mnDiemSV.setEnabled(true);
        mnSV.setEnabled(false);
        setVisible(false);
    }
    public void QuanLy(){
        mnDiemSV.setEnabled(false);
        mnSV.setEnabled(true);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnDN;
    private javax.swing.JMenuItem mnDiemSV;
    private javax.swing.JMenu mnQL;
    private javax.swing.JMenuItem mnSV;
    // End of variables declaration//GEN-END:variables

   
}
